import type { AnalysisSnapshot, MtfFrame } from '@/types/analysis';

const frame = (timeframe: string, trend: MtfFrame['trend']): MtfFrame => ({
  timeframe,
  ready: true,
  candle_time: 1_000,
  trend,
  structure: trend,
  directional_regime: trend === 'bullish' ? 'uptrend' : trend === 'bearish' ? 'downtrend' : 'range',
  volatility_regime: 'normal',
});

/** Compact but complete ready snapshot (values shaped like the real backend payload). */
export function readySnapshot(overrides: Partial<AnalysisSnapshot> = {}): AnalysisSnapshot {
  return {
    kind: 'full',
    symbol: 'BTCUSDT',
    timeframe: '5m',
    analysis_ready: true,
    reason: null,
    candle_time: 10_000,
    forming_time: 10_300,
    price: 105,
    generated_at: '2026-10-04T08:00:00Z',
    candles_analyzed: 999,
    trend: {
      direction: 'bullish',
      score: 0.7,
      emas: [20, 50, 100, 200].map((period) => ({
        period,
        value: 100,
        slope: 0.1,
        normalized_slope: 0.05,
        distance_atr: 1,
      })),
      stack: 'bullish',
      alignment_score: 3,
      spread_atr: 2,
      spread_change_atr: 0.3,
      spread_state: 'expanding',
      price_above_ema200: true,
    },
    regime: {
      primary: 'uptrend',
      directional: 'uptrend',
      volatility: 'normal',
      inputs: { trend_score: 0.7, efficiency_ratio: 0.3 },
    },
    volatility: {
      atr: 2,
      atr_pct: 0.19,
      atr_percentile: 55,
      range_atr: 1.1,
      realized_vol: 0.1,
      regime: 'normal',
    },
    momentum: {
      rsi: 61.4,
      rsi_slope: 1.2,
      rsi_cross_50: null,
      rsi_overbought: false,
      rsi_oversold: false,
      roc: 0.4,
      impulse_atr: 1.2,
      acceleration: 0.1,
      divergence: null,
    },
    volume: {
      volume: 30,
      average: 15,
      relative: 2.0,
      zscore: 2.5,
      percentile: 96,
      spike: true,
      contraction: false,
    },
    candle: null,
    forming_candle: null,
    swing_structure: {
      layer: 'swing',
      direction: 'bullish',
      pivots: [
        {
          id: 'swing:pivot:high:9000',
          layer: 'swing',
          side: 'high',
          type: 'HH',
          price: 110,
          index: 1,
          time: 9_000,
          confirmed_index: 6,
          confirmed_time: 10_800,
          status: 'confirmed',
        },
      ],
      events: [
        {
          id: 'swing:BOS:bullish:9600',
          layer: 'swing',
          type: 'BOS',
          direction: 'bullish',
          level: 104,
          level_index: 0,
          level_time: 8_000,
          index: 3,
          time: 9_600,
          confirmed_time: 9_900,
          close: 105,
          displacement: 70,
          relative_volume: 1.8,
          volume_confirmed: true,
          status: 'confirmed',
        },
      ],
      last_event: null,
      protected_high: null,
      protected_low: {
        id: 'swing:protected:low',
        layer: 'swing',
        side: 'low',
        price: 98,
        index: 0,
        time: 8_500,
        created_time: 9_900,
        status: 'active',
        ended_time: null,
        active: true,
      },
      break_high: 110,
      break_low: 98,
    },
    internal_structure: {
      layer: 'internal',
      direction: 'bearish',
      pivots: [],
      events: [],
      last_event: null,
      protected_high: null,
      protected_low: null,
      break_high: null,
      break_low: null,
    },
    liquidity: {
      pools: [
        {
          id: 'eqh:1:2',
          side: 'buy_side',
          source: 'equal_highs',
          level: 111,
          index: 0,
          time: 8_200,
          confirmed_time: 9_000,
          touches: 2,
          status: 'active',
          ended_index: null,
          ended_time: null,
        },
        {
          id: 'pool:sell:1',
          side: 'sell_side',
          source: 'swing_low',
          level: 97,
          index: 0,
          time: 8_100,
          confirmed_time: 9_000,
          touches: 1,
          status: 'swept',
          ended_index: 2,
          ended_time: 9_300,
        },
      ],
      equal_highs: [],
      equal_lows: [],
      sweeps: [],
      active_buy_side: 3,
      active_sell_side: 2,
      nearest_buy_side: 111,
      nearest_sell_side: 97,
    },
    fair_value_gaps: [
      {
        id: 'fvg:bullish_fvg:9300',
        type: 'bullish_fvg',
        top: 103,
        bottom: 101,
        mid: 102,
        size: 2,
        index: 2,
        time: 9_300,
        created_index: 3,
        confirmed_time: 9_900,
        size_atr: 1,
        displacement: 80,
        quality: 78,
        filled: 0.2,
        status: 'active',
        status_detail: 'confirmed',
        mitigated_time: null,
        ended_time: null,
      },
      {
        id: 'fvg:bearish_fvg:8000',
        type: 'bearish_fvg',
        top: 99,
        bottom: 98.5,
        mid: 98.75,
        size: 0.5,
        index: 0,
        time: 8_000,
        created_index: 1,
        confirmed_time: 8_600,
        size_atr: 0.4,
        displacement: 40,
        quality: 0,
        filled: 1,
        status: 'invalidated',
        status_detail: 'invalidated',
        mitigated_time: null,
        ended_time: 9_000,
      },
    ],
    order_blocks: [
      {
        id: 'ob:bullish_ob:8400',
        type: 'bullish_ob',
        top: 100,
        bottom: 98,
        mid: 99,
        index: 0,
        time: 8_400,
        created_index: 3,
        confirmed_time: 9_900,
        source_event_id: 'swing:BOS:bullish:9600',
        layer: 'swing',
        displacement: 70,
        quality: 84,
        touches: 1,
        status: 'mitigated',
        mitigated_time: 10_000,
        ended_time: null,
      },
    ],
    premium_discount: {
      layer: 'swing',
      high: 110,
      high_time: 9_000,
      low: 98,
      low_time: 8_500,
      equilibrium: 104,
      equilibrium_upper: 104.6,
      equilibrium_lower: 103.4,
      position: 58.3,
      zone: 'premium',
    },
    ote: {
      direction: 'bullish',
      layer: 'swing',
      impulse_start: 98,
      impulse_start_time: 8_500,
      impulse_end: 110,
      impulse_end_time: 9_000,
      upper: 102.6,
      lower: 100.5,
      focus: 101.5,
      active: true,
      price_in_zone: false,
    },
    multi_timeframe: {
      execution: frame('5m', 'bullish'),
      higher: [frame('15m', 'bullish'), frame('1h', 'neutral')],
      directional_alignment: 'bullish',
      structure_alignment: 'bullish',
      volatility_aligned: true,
      regime_alignment: 'bullish',
    },
    developing: {
      swing_pivots: [],
      internal_pivots: [],
      swing_breaks: [],
      internal_breaks: [],
      sweeps: [],
      fair_value_gaps: [],
    },
    counts: { swing_bos: 1 },
    debug: { last_index: 998 },
    ...overrides,
  };
}

export function notReady(reason: string, symbol = 'BTCUSDT', timeframe = '5m'): AnalysisSnapshot {
  return {
    kind: 'full',
    symbol,
    timeframe,
    analysis_ready: false,
    reason,
    candle_time: null,
    forming_time: null,
    price: null,
  };
}

/** Narrow an optional fixture field in tests (throws instead of using `!`). */
export function must<T>(value: T | null | undefined): T {
  if (value === null || value === undefined) throw new Error('fixture field missing');
  return value;
}
