import raw from '@/test/fixtures/frozen-signals.json';
import type { CandleBar } from '@/types/market';
import type { SignalDTO } from '@/types/signal';

/**
 * Real frozen-engine output on real OKX ETHUSDT 15m candles, generated by
 * backend/tests/signals/ui_fixtures.py (a backend test fails if this ever drifts).
 */
interface Case {
  candles: CandleBar[];
  trigger_time: number;
  signal_at_confirmation: SignalDTO;
  signal: SignalDTO;
  signals: SignalDTO[];
}

const data = raw as unknown as { strategy_version: string; buy: Case; sell: Case };

export const FIXTURE_STRATEGY = data.strategy_version;
export const BUY = data.buy.signal_at_confirmation;
export const SELL = data.sell.signal_at_confirmation;
export const BUY_HISTORY = data.buy.signals;
export const SELL_HISTORY = data.sell.signals;
export const BUY_CANDLES = data.buy.candles;
export const SELL_CANDLES = data.sell.candles;
