#!/usr/bin/env node
/**
 * Browser E2E of the chart signal UX against the packaged-style app: the backend in desktop
 * mode serving the production React build (same origin), real OKX market data.
 *
 *   node scripts/e2e_chart_signals.mjs --url http://127.0.0.1:PORT --out <screenshot dir>
 *
 * Live part: first-run admin, both charts render, status cards, legend, layer toggles,
 * the 1m/5m/10m execution-timing bar and panel (v1.1), no console errors, no RTL overflow at
 * 1366x768 and 1920x1080.
 * Fixture part (test mode only — the shipped app has no fixture mode): the chart-signals
 * and candles responses of ONE chart are replaced by the real frozen-engine output in
 * frontend/src/test/fixtures/frozen-signals.json (generated by the backend replay), to
 * render the confirmed BUY and SELL exactly as the engine produced them.
 *
 * Playwright is resolved from PLAYWRIGHT_MODULE or the global npm root.
 */
import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { mkdirSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const args = Object.fromEntries(
  process.argv
    .slice(2)
    .reduce(
      (acc, v, i, a) =>
        v.startsWith("--") ? [...acc, [v.slice(2), a[i + 1]]] : acc,
      [],
    ),
);
const BASE = args.url ?? "http://127.0.0.1:8765";
const OUT = args.out ?? path.join(ROOT, "e2e-screenshots");
mkdirSync(OUT, { recursive: true });
const require = createRequire(import.meta.url);
const pw = require(
  process.env.PLAYWRIGHT_MODULE ??
    path.join(execSync("npm root -g").toString().trim(), "playwright"),
);
const fixture = JSON.parse(
  readFileSync(
    path.join(ROOT, "frontend/src/test/fixtures/frozen-signals.json"),
    "utf8",
  ),
);

const results = [];
function check(name, ok, detail = "") {
  results.push([name, ok]);
  console.log(
    `[${ok ? "PASS" : "FAIL"}] ${name}${detail ? " - " + detail : ""}`,
  );
}

const browser = await pw.chromium.launch(
  process.env.CHROMIUM_PATH
    ? { executablePath: process.env.CHROMIUM_PATH }
    : process.env.CHROMIUM_CHANNEL // e.g. "chrome" on CI runners (installed Google Chrome)
      ? { channel: process.env.CHROMIUM_CHANNEL }
      : {},
);
const context = await browser.newContext({
  viewport: { width: 1366, height: 768 },
  locale: "ar",
});
const page = await context.newPage();
const consoleErrors = [];
page.on("console", (m) => {
  if (m.type() === "error") consoleErrors.push(m.text());
});
page.on("pageerror", (e) => consoleErrors.push(String(e)));

// --- first-run admin (password generated here, never printed) ---------------------------------
const setup = await page.request.get(`${BASE}/api/v1/auth/setup`);
const password =
  process.env.E2E_ADMIN_PASSWORD ?? randomBytes(18).toString("base64url");
if ((await setup.json()).needs_setup) {
  const created = await page.request.post(`${BASE}/api/v1/auth/setup`, {
    data: { username: "e2e_admin", password },
  });
  check("first-run admin created", created.status() === 201);
} else if (process.env.E2E_ADMIN_PASSWORD) {
  const login = await page.request.post(`${BASE}/api/v1/auth/login`, {
    data: { username: "e2e_admin", password },
  });
  check("admin signed in", login.ok());
}

async function chartPanel(id) {
  return page.locator(`section[data-chart="${id}"]`);
}

async function waitReady(id) {
  await page.waitForSelector(`section[data-chart="${id}"][data-load="ready"]`, {
    timeout: 90_000,
  });
}

async function noOverflow(label) {
  const bad = await page.evaluate(() =>
    [
      ...document.querySelectorAll(
        '[data-testid="chart-signal-status"], [data-testid="execution-status"]',
      ),
    ]
      .filter((el) => el.scrollWidth > el.clientWidth + 1)
      .map((el) => el.closest("section")?.getAttribute("data-chart")),
  );
  check(
    `${label}: status cards fit, no RTL overflow`,
    bad.length === 0,
    bad.join(","),
  );
  const pageOverflow = await page.evaluate(
    () =>
      document.documentElement.scrollWidth >
      document.documentElement.clientWidth + 1,
  );
  check(`${label}: no horizontal page scroll`, !pageOverflow);
}

// --- live: default charts (BTCUSDT 15m Strategy 4.3, ETHUSDT 5m execution timing) ------------
await page.goto(BASE, { waitUntil: "networkidle" });
await waitReady("primary");
await waitReady("secondary");
for (const id of ["primary", "secondary"]) {
  const canvases = await (await chartPanel(id)).locator("canvas").count();
  check(`${id} chart renders`, canvases > 0, `${canvases} canvases`);
}
await page.waitForSelector(
  'section[data-chart="primary"][data-analysis="ready"]',
  { timeout: 90_000 },
);
const primaryState = await page
  .locator('section[data-chart="primary"] [data-testid="chart-signal-status"]')
  .getAttribute("data-state");
check(
  "live 15m status is canonical and never 'inactive' (Strategy 4.3 always on)",
  ["neutral", "buy", "sell"].includes(primaryState),
  primaryState,
);
// v1.2: live signal engine health + market scanner
await page.waitForFunction(
  () =>
    ["running", "degraded"].includes(
      document.querySelector('[data-testid="engine-status"]')?.getAttribute("data-state") ?? "",
    ),
  null,
  { timeout: 120_000 },
);
const engineText = await page.getByTestId("engine-status").innerText();
check("engine status: «محرك الإشارات» نشط", engineText.includes("نشط"), engineText.split("\n")[1]);
for (const label of ["آخر تحديث للسوق", "آخر شمعة تم تحليلها", "آخر فحص للفرص", "آخر إشارة",
  "عدد الفرص المفتوحة", "عدد الإشارات اليوم", "Telegram"])
  check(`engine status shows «${label}»`, engineText.includes(label));
check(
  "no «متابعة الإشارات غير نشطة» anywhere",
  !(await page.locator("body").innerText()).includes("غير نشطة"),
);
const scanner = page.getByTestId("opportunity-scanner");
check("«أفضل الفرص الآن» scanner present", (await scanner.count()) === 1);
const rows = scanner.getByTestId("scanner-row");
const nRows = await rows.count();
check(
  "scanner lists opportunities or says honestly there are none",
  nRows > 0 || (await page.getByTestId("scanner-empty").count()) === 1,
  `${nRows} rows`,
);
if (primaryState === "neutral") {
  const panelText = await page.getByTestId("entry-blockers").innerText();
  check(
    "no-trade line + best opportunity fallback",
    panelText.includes("لا توجد فرصة مناسبة على هذا الفريم حالياً") &&
      (await page.getByTestId("best-opportunity").count()) === 1,
  );
}
if (nRows > 0) {
  const first = rows.first();
  const sym = await first.getAttribute("data-symbol");
  const tf = await first.getAttribute("data-timeframe");
  await first.click();
  const opened = await page
    .waitForFunction(
      ([s, t]) => {
        const raw = localStorage.getItem("wesetrade.charts");
        const sel = raw ? JSON.parse(raw).state?.charts?.primary : null;
        return sel?.symbol === s && sel?.timeframe === t;
      },
      [sym, tf],
      { timeout: 15_000 },
    )
    .then(() => true)
    .catch(() => false);
  check(`scanner click opens ${sym} ${tf} on the focused chart`, opened);
  await page.waitForFunction(
    () => document.querySelector('[data-testid="signal-badge"]') !== null,
    null,
    { timeout: 30_000 },
  );
  const tierOk =
    (await page.getByTestId("signal-tier").count()) === 1 ||
    (await page.getByTestId("signal-badge").getAttribute("data-decision")) === "NEUTRAL";
  check("opened opportunity shows «جودة الفرصة» tier", tierOk);
  await page.screenshot({ path: path.join(OUT, "01b-opportunity-1366.png") });
  // back to the default stream for the remaining checks
  await page.evaluate(() => {
    localStorage.removeItem("wesetrade.charts");
  });
  await page.reload({ waitUntil: "networkidle" });
  await waitReady("primary");
  await waitReady("secondary");
}
const execBar = page.locator(
  'section[data-chart="secondary"] [data-testid="execution-status"]',
);
await page.waitForFunction(
  () =>
    document
      .querySelector('section[data-chart="secondary"]')
      ?.getAttribute("data-execution") !== "none",
  null,
  { timeout: 90_000 },
);
const execDecision = await execBar.getAttribute("data-decision");
const secondaryText = await execBar.innerText();
check(
  "5m: execution timing bar with a canonical decision",
  ["BUY", "SELL", "WAIT", "ENTRY_MISSED", "NO_SETUP"].includes(execDecision),
  execDecision,
);
check(
  "5m: no analysis-only / experimental wording",
  !/تحليل فقط|للتحليل فقط|غير مُثبت|تجريبي/.test(secondaryText),
);
check(
  "5m: markers only from persisted execution signals",
  /^\d+$/.test(
    (await (await chartPanel("secondary")).getAttribute("data-markers")) ?? "",
  ),
);
await (await chartPanel("secondary")).dispatchEvent("pointerdown");
check(
  "5m focused: execution panel (decision, timing strength, reasons)",
  (await page.getByTestId("execution-panel").count()) === 1 &&
    (await page.getByTestId("execution-panel").innerText()).includes(
      "قوة توقيت الدخول",
    ),
);
await (await chartPanel("primary")).dispatchEvent("pointerdown");
await noOverflow("1366x768 live");
await page.screenshot({ path: path.join(OUT, "01-live-1366.png") });

// legend
await page
  .locator('section[data-chart="primary"]')
  .getByRole("button", { name: "شرح الشارت" })
  .click();
const dialog = page.getByRole("dialog", { name: "شرح الشارت" });
check(
  "legend opens with the authority statement",
  (await dialog.innerText()).includes(
    "قرار BUY أو SELL يصدر حصراً من محرك إشارات Wese Trade",
  ),
);
check(
  "legend explains CHoCH in Arabic",
  (await dialog.innerText()).includes("تغير في سلوك/بنية السوق"),
);
await page.screenshot({ path: path.join(OUT, "02-legend.png") });
await page.keyboard.press("Escape");
check("legend closes", (await dialog.count()) === 0);

// layer toggles
const layers = page
  .locator('section[data-chart="primary"]')
  .getByRole("button", { name: "طبقات التحليل" });
await layers.click();
const structure = page.getByRole("menuitemcheckbox", {
  name: /Market Structure/,
});
const before = await structure.getAttribute("aria-checked");
await structure.click();
const after = await structure.getAttribute("aria-checked");
check("overlay toggle works", before !== after);
await structure.click();
await page.keyboard.press("Escape");

// Fixture mode only: the live ETHUSDT 15m stream (real candles/analysis/signals of TODAY)
// is withheld from the browser so the fixture candles render alone; every other stream
// (the secondary chart) stays live.
let fixtureMode = false;
let execFixture = false;
let browserSocket = null;
await page.routeWebSocket(/\/api\/v1\/ws/, (ws) => {
  browserSocket = ws;
  const server = ws.connectToServer();
  ws.onMessage((m) => server.send(m));
  server.onMessage((m) => {
    if ((fixtureMode || execFixture) && typeof m === "string") {
      try {
        const e = JSON.parse(m);
        if (fixtureMode && e.data?.symbol === "ETHUSDT" && e.data?.timeframe === "15m") return;
        if (
          execFixture &&
          e.type === "execution.update" &&
          e.data?.symbol === "ETHUSDT" &&
          e.data?.timeframe === "5m"
        )
          return;
      } catch {
        /* not JSON: forward */
      }
    }
    ws.send(m);
  });
});

// --- test mode only: an execution SELL (15m Strategy 4.2 parent -> 5m confirmation) ----------
// Injected over the WebSocket for the LIVE secondary ETHUSDT 5m chart, on its last closed
// candle: marker, decision bar, plan and the execution panel must render it exactly.
await page.reload({ waitUntil: "networkidle" });
await waitReady("primary");
await waitReady("secondary");
const lastClosed = Math.floor(Date.now() / 1000 / 300) * 300 - 300;
const price =
  Number(
    await page
      .locator('section[data-chart="secondary"] [data-last-close]')
      .first()
      .getAttribute("data-last-close"),
  ) || 2500;
const sellParent = {
  signal_id: "e2e-ETHUSDT-15m-short", strategy: "Wese Trade Forward 4.2",
  strategy_version: "wese-trade-forward-4.2-a03e20f1d4", fingerprint: "4.2-a03e20f",
  symbol: "ETHUSDT", timeframe: "15m", side: -1, family: "TREND_CONTINUATION", score: 79.2,
  state: "confirmed", confirmed_time: lastClosed - 900, entry_low: price, entry_high: price * 1.002,
  entry: price * 1.001, stop: price * 1.008, invalidation: price * 1.008,
  targets: [price * 0.992, price * 0.987, price * 0.98],
}; // prettier-ignore
const sellPlan = {
  side: -1, entry: price, parent_entry: sellParent.entry, stop: sellParent.stop,
  parent_stop: sellParent.stop, stop_source: "parent", targets: sellParent.targets,
  target_sources: ["parent_tp1", "parent_tp2", "parent_tp3"], rr: [1.0, 1.63, 2.5],
}; // prettier-ignore
const sellState = {
  symbol: "ETHUSDT", timeframe: "5m", execution_version: "wese-trade-execution-1.1",
  evaluation: {
    candle_time: lastClosed, decision: "SELL", decision_ar: "بيع", score: 78,
    score_band: "strong", side: -1, headline: "تم تأكيد توقيت الدخول للصفقة الهابطة.",
    reasons: ["اتجاه 15m هابط (Strategy 4.2)", "تم تأكيد CHoCH داخلي هابط"], cautions: [],
    components: {}, parent: sellParent, plan: sellPlan, trigger: "choch", micro: null,
  },
  signal: {
    id: "x-e2e-sell", symbol: "ETHUSDT", timeframe: "5m", side: -1, score: 78,
    confirmed_time: lastClosed + 300, candle_time: lastClosed, valid_until: lastClosed + 600,
    plan: sellPlan, parent: sellParent, reasons: ["اتجاه 15m هابط (Strategy 4.2)"],
    trigger: "choch", state: "ready", state_ar: "جاهز للدخول", state_time: lastClosed + 300,
    entered_time: null, targets_hit: 0, closed_time: null,
    execution_version: "wese-trade-execution-1.1", history: [[lastClosed + 300, "ready"]],
  },
  markers: [{ id: "x-e2e-sell", time: lastClosed, side: -1, state: "ready" }],
  overlay: { ema: { 20: price, 50: price * 1.001, 200: price * 1.01 }, levels: [] },
  micro: null,
}; // prettier-ignore
execFixture = true;
browserSocket?.send(
  JSON.stringify({ type: "execution.update", timestamp: new Date().toISOString(), data: sellState }),
);
await page.waitForTimeout(1200);
const execSell = page.locator(
  'section[data-chart="secondary"] [data-testid="execution-status"]',
);
check(
  "execution SELL: decision bar «SELL — بيع» with Entry/SL/TP and timing",
  (await execSell.getAttribute("data-decision")) === "SELL" &&
    (await execSell.innerText()).includes("SELL — بيع") &&
    (await execSell.innerText()).includes("78/100"),
);
check(
  "execution SELL: marker on the confirmation candle",
  (await (await chartPanel("secondary")).getAttribute("data-markers")) === "1",
);
await (await chartPanel("secondary")).dispatchEvent("pointerdown");
const execPanelText = await page.getByTestId("execution-panel").innerText();
check(
  "execution SELL: panel shows parent 15m, confirmed timing, plan and reasons",
  execPanelText.includes("15m Trend Continuation") &&
    execPanelText.includes("مؤكد") &&
    execPanelText.includes("اتجاه 15m هابط") &&
    execPanelText.includes("78 / 100"),
);
await page.screenshot({ path: path.join(OUT, "02b-execution-sell.png") });
execFixture = false;
await (await chartPanel("primary")).dispatchEvent("pointerdown");

// --- fixture mode: the engine's real BUY on the primary chart ---------------------------------
let current = null;
await page.route(
  /\/api\/v1\/markets\/ETHUSDT\/candles\?.*timeframe=15m/,
  (route) =>
    current
      ? route.fulfill({
          json: {
            symbol: "ETHUSDT",
            timeframe: "15m",
            candles: current.candles,
          },
        })
      : route.continue(),
);
await page.route(
  /\/api\/v1\/strategy43\/chart-signals\?symbol=ETHUSDT&timeframe=15m/,
  (route) =>
    current
      ? route.fulfill({
          json: {
            symbol: "ETHUSDT",
            timeframe: "15m",
            signal_capable: true,
            items: current.signals,
          },
        })
      : route.continue(),
);

async function showFixture(kind, signals) {
  fixtureMode = true;
  current = { candles: fixture[kind].candles, signals };
  await page.evaluate(() => {
    const raw = JSON.parse(
      localStorage.getItem("wesetrade.charts") ?? '{"state":{},"version":1}',
    );
    raw.state.charts = {
      primary: { symbol: "ETHUSDT", timeframe: "15m" },
      secondary: { symbol: "BTCUSDT", timeframe: "1h" },
    };
    localStorage.setItem("wesetrade.charts", JSON.stringify(raw));
  });
  await page.reload({ waitUntil: "networkidle" });
  await waitReady("primary");
  await waitReady("secondary");
  await page.waitForTimeout(1500);
}

async function insideViewport(locator) {
  const box = await locator.boundingBox();
  const vp = page.viewportSize();
  return (
    box !== null &&
    box.x >= 0 &&
    box.y >= 0 &&
    box.x + box.width <= vp.width + 1 &&
    box.y + box.height <= vp.height + 1
  );
}

async function legendVisibleIn(id) {
  const strip = page.locator(
    `section[data-chart="${id}"] [data-testid="chart-signal-status"]`,
  );
  const button = strip.getByRole("button", { name: "شرح الشارت" });
  const s = await strip.boundingBox();
  const b = await button.boundingBox();
  return s && b && b.x >= s.x - 1 && b.x + b.width <= s.x + s.width + 1;
}

async function hoverMarker(expectSide) {
  const box = await page
    .locator('section[data-chart="primary"] canvas')
    .first()
    .boundingBox();
  for (let x = box.x + box.width - 80; x > box.x + 10; x -= 3) {
    await page.mouse.move(x, box.y + box.height / 2);
    const card = page.getByTestId("signal-marker-card");
    if (
      (await card.count()) > 0 &&
      (await card.innerText()).includes(expectSide)
    )
      return card;
  }
  return null;
}

const BUY = fixture.buy.signal_at_confirmation;
await showFixture("buy", fixture.buy.signals);
const buyStatus = page.locator(
  'section[data-chart="primary"] [data-testid="chart-signal-status"]',
);
check(
  "BUY fixture: status «BUY — شراء»",
  (await buyStatus.getAttribute("data-state")) === "buy",
);
const buyText = await buyStatus.innerText();
check(
  "BUY fixture: Entry/SL/TP1-3 + strength shown",
  ["2,485.14", "2,467.73", "2,508.38", "2,518.31", "2,558.56", "81/100"].every(
    (v) => buyText.includes(v),
  ),
);
check(
  "BUY fixture: persisted markers (1 closed + 1 active) on the chart",
  (await (await chartPanel("primary")).getAttribute("data-markers")) === "2",
);
const secondary = page.locator(
  'section[data-chart="secondary"] [data-testid="chart-signal-status"]',
);
check(
  "two charts independent (secondary BTCUSDT 1h: own state, no leaked markers)",
  (await (await chartPanel("secondary")).getAttribute("data-symbol")) ===
    "BTCUSDT" &&
    (await (await chartPanel("secondary")).getAttribute("data-markers")) ===
      "0" &&
    (await secondary.getAttribute("data-state")) !== "buy",
);
await page.screenshot({ path: path.join(OUT, "03-buy-fixture.png") });
const buyCard = await hoverMarker("شراء BUY");
check("BUY marker tooltip on hover", buyCard !== null);
check(
  "BUY status: legend button stays visible",
  await legendVisibleIn("primary"),
);
if (buyCard)
  check(
    "BUY tooltip fully visible (not clipped)",
    await insideViewport(buyCard),
  );
if (buyCard) {
  const t = await buyCard.innerText();
  check(
    "BUY tooltip: fingerprint + not a probability",
    t.includes("4.2-a03e20f") && t.includes("غير معايرة"),
  );
  await page.screenshot({ path: path.join(OUT, "04-buy-tooltip.png") });
}
check(
  "BUY id matches engine fixture",
  BUY.trigger_time === Date.parse("2026-09-18T05:00:00Z") / 1000,
);

// --- fixture mode: the engine's real SELL (at confirmation, then after it was stopped) --------
await page.mouse.move(5, 5);
await showFixture("sell", [fixture.sell.signal_at_confirmation]);
const sellStatus = page.locator(
  'section[data-chart="primary"] [data-testid="chart-signal-status"]',
);
check(
  "SELL fixture: status «SELL — بيع»",
  (await sellStatus.getAttribute("data-state")) === "sell",
);
const sellText = await sellStatus.innerText();
check(
  "SELL fixture: plan values",
  ["1,876.00", "1,889.13", "1,857.96", "1,848.16", "1,835.03", "79/100"].every(
    (v) => sellText.includes(v),
  ),
);
await page.screenshot({ path: path.join(OUT, "05-sell-fixture.png") });
const sellCard = await hoverMarker("بيع SELL");
check("SELL marker tooltip on hover", sellCard !== null);
if (sellCard)
  check(
    "SELL tooltip fully visible (not clipped)",
    await insideViewport(sellCard),
  );
if (sellCard)
  await page.screenshot({ path: path.join(OUT, "06-sell-tooltip.png") });

await page.mouse.move(5, 5);
await showFixture("sell", fixture.sell.signals);
check(
  "closed SELL: marker kept, status back to neutral (no plan lines)",
  (await sellStatus.getAttribute("data-state")) === "neutral" &&
    (await (await chartPanel("primary")).getAttribute("data-markers")) === "1",
);
await page.screenshot({ path: path.join(OUT, "07-sell-closed.png") });

// --- desktop resolution 1920x1080 --------------------------------------------------------------
await page.setViewportSize({ width: 1920, height: 1080 });
await page.waitForTimeout(800);
await noOverflow("1920x1080");
await page.screenshot({ path: path.join(OUT, "08-1920.png") });

current = null;
fixtureMode = false;
const relevant = consoleErrors.filter((e) => !/favicon/i.test(e));
check(
  "no console errors",
  relevant.length === 0,
  relevant.slice(0, 3).join(" | "),
);

await browser.close();
const failed = results.filter(([, ok]) => !ok);
console.log(
  `== chart signal E2E: ${results.length - failed.length}/${results.length} checks passed`,
);
process.exit(failed.length ? 1 : 0);
