#!/usr/bin/env node
/**
 * Browser E2E of the chart signal UX against the packaged-style app: the backend in desktop
 * mode serving the production React build (same origin), real OKX market data.
 *
 *   node scripts/e2e_chart_signals.mjs --url http://127.0.0.1:PORT --out <screenshot dir>
 *
 * Live part: first-run admin, both charts render, status cards, legend, layer toggles,
 * analysis-only timeframe, no console errors, no RTL overflow at 1366x768 and 1920x1080.
 * Fixture part (test mode only — the shipped app has no fixture mode): the chart-signals
 * and candles responses of ONE chart are replaced by the real frozen-engine output in
 * frontend/src/test/fixtures/frozen-signals.json (generated by the backend replay), to
 * render the confirmed BUY and SELL exactly as the engine produced them.
 *
 * Playwright is resolved from PLAYWRIGHT_MODULE or the global npm root.
 */
import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { mkdirSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const args = Object.fromEntries(
  process.argv
    .slice(2)
    .reduce(
      (acc, v, i, a) =>
        v.startsWith("--") ? [...acc, [v.slice(2), a[i + 1]]] : acc,
      [],
    ),
);
const BASE = args.url ?? "http://127.0.0.1:8765";
const OUT = args.out ?? path.join(ROOT, "e2e-screenshots");
mkdirSync(OUT, { recursive: true });
const require = createRequire(import.meta.url);
const pw = require(
  process.env.PLAYWRIGHT_MODULE ??
    path.join(execSync("npm root -g").toString().trim(), "playwright"),
);
const fixture = JSON.parse(
  readFileSync(
    path.join(ROOT, "frontend/src/test/fixtures/frozen-signals.json"),
    "utf8",
  ),
);

const results = [];
function check(name, ok, detail = "") {
  results.push([name, ok]);
  console.log(
    `[${ok ? "PASS" : "FAIL"}] ${name}${detail ? " - " + detail : ""}`,
  );
}

const browser = await pw.chromium.launch(
  process.env.CHROMIUM_PATH
    ? { executablePath: process.env.CHROMIUM_PATH }
    : process.env.CHROMIUM_CHANNEL // e.g. "chrome" on CI runners (installed Google Chrome)
      ? { channel: process.env.CHROMIUM_CHANNEL }
      : {},
);
const context = await browser.newContext({
  viewport: { width: 1366, height: 768 },
  locale: "ar",
});
const page = await context.newPage();
const consoleErrors = [];
page.on("console", (m) => {
  if (m.type() === "error") consoleErrors.push(m.text());
});
page.on("pageerror", (e) => consoleErrors.push(String(e)));

// --- first-run admin (password generated here, never printed) ---------------------------------
const setup = await page.request.get(`${BASE}/api/v1/auth/setup`);
const password =
  process.env.E2E_ADMIN_PASSWORD ?? randomBytes(18).toString("base64url");
if ((await setup.json()).needs_setup) {
  const created = await page.request.post(`${BASE}/api/v1/auth/setup`, {
    data: { username: "e2e_admin", password },
  });
  check("first-run admin created", created.status() === 201);
} else if (process.env.E2E_ADMIN_PASSWORD) {
  const login = await page.request.post(`${BASE}/api/v1/auth/login`, {
    data: { username: "e2e_admin", password },
  });
  check("admin signed in", login.ok());
}

async function chartPanel(id) {
  return page.locator(`section[data-chart="${id}"]`);
}

async function waitReady(id) {
  await page.waitForSelector(`section[data-chart="${id}"][data-load="ready"]`, {
    timeout: 90_000,
  });
}

async function noOverflow(label) {
  const bad = await page.evaluate(() =>
    [...document.querySelectorAll('[data-testid="chart-signal-status"]')]
      .filter((el) => el.scrollWidth > el.clientWidth + 1)
      .map((el) => el.closest("section")?.getAttribute("data-chart")),
  );
  check(
    `${label}: status cards fit, no RTL overflow`,
    bad.length === 0,
    bad.join(","),
  );
  const pageOverflow = await page.evaluate(
    () =>
      document.documentElement.scrollWidth >
      document.documentElement.clientWidth + 1,
  );
  check(`${label}: no horizontal page scroll`, !pageOverflow);
}

// --- live: default charts (BTCUSDT 15m signals-enabled, ETHUSDT 5m analysis-only) -------------
await page.goto(BASE, { waitUntil: "networkidle" });
await waitReady("primary");
await waitReady("secondary");
for (const id of ["primary", "secondary"]) {
  const canvases = await (await chartPanel(id)).locator("canvas").count();
  check(`${id} chart renders`, canvases > 0, `${canvases} canvases`);
}
await page.waitForSelector(
  'section[data-chart="primary"][data-analysis="ready"]',
  { timeout: 90_000 },
);
const primaryState = await page
  .locator('section[data-chart="primary"] [data-testid="chart-signal-status"]')
  .getAttribute("data-state");
check(
  "live 15m status is canonical (neutral unless the engine has an open signal)",
  ["neutral", "buy", "sell", "paused"].includes(primaryState),
  primaryState,
);
const secondaryText = await page
  .locator(
    'section[data-chart="secondary"] [data-testid="chart-signal-status"]',
  )
  .innerText();
check(
  "5m: analysis only, signals disabled",
  secondaryText.includes("هذا الفريم للتحليل فقط") &&
    secondaryText.includes("الإشارات غير مفعلة على هذا الفريم"),
);
check(
  "5m: no BUY/SELL markers",
  (await (await chartPanel("secondary")).getAttribute("data-markers")) === "0",
);
await noOverflow("1366x768 live");
await page.screenshot({ path: path.join(OUT, "01-live-1366.png") });

// legend
await page
  .locator('section[data-chart="primary"]')
  .getByRole("button", { name: "شرح الشارت" })
  .click();
const dialog = page.getByRole("dialog", { name: "شرح الشارت" });
check(
  "legend opens with the authority statement",
  (await dialog.innerText()).includes(
    "قرار BUY أو SELL يصدر حصراً من محرك إشارات Wese Trade",
  ),
);
check(
  "legend explains CHoCH in Arabic",
  (await dialog.innerText()).includes("تغير في سلوك/بنية السوق"),
);
await page.screenshot({ path: path.join(OUT, "02-legend.png") });
await page.keyboard.press("Escape");
check("legend closes", (await dialog.count()) === 0);

// layer toggles
const layers = page
  .locator('section[data-chart="primary"]')
  .getByRole("button", { name: "طبقات التحليل" });
await layers.click();
const structure = page.getByRole("menuitemcheckbox", {
  name: /Market Structure/,
});
const before = await structure.getAttribute("aria-checked");
await structure.click();
const after = await structure.getAttribute("aria-checked");
check("overlay toggle works", before !== after);
await structure.click();
await page.keyboard.press("Escape");

// Fixture mode only: the live ETHUSDT 15m stream (real candles/analysis/signals of TODAY)
// is withheld from the browser so the fixture candles render alone; every other stream
// (the secondary chart) stays live.
let fixtureMode = false;
await page.routeWebSocket(/\/api\/v1\/ws/, (ws) => {
  const server = ws.connectToServer();
  ws.onMessage((m) => server.send(m));
  server.onMessage((m) => {
    if (fixtureMode && typeof m === "string") {
      try {
        const e = JSON.parse(m);
        if (e.data?.symbol === "ETHUSDT" && e.data?.timeframe === "15m") return;
      } catch {
        /* not JSON: forward */
      }
    }
    ws.send(m);
  });
});

// --- fixture mode: the engine's real BUY on the primary chart ---------------------------------
let current = null;
await page.route(
  /\/api\/v1\/markets\/ETHUSDT\/candles\?.*timeframe=15m/,
  (route) =>
    current
      ? route.fulfill({
          json: {
            symbol: "ETHUSDT",
            timeframe: "15m",
            candles: current.candles,
          },
        })
      : route.continue(),
);
await page.route(
  /\/api\/v1\/forward-test\/chart-signals\?symbol=ETHUSDT&timeframe=15m/,
  (route) =>
    current
      ? route.fulfill({
          json: {
            symbol: "ETHUSDT",
            timeframe: "15m",
            signal_capable: true,
            items: current.signals,
          },
        })
      : route.continue(),
);

async function showFixture(kind, signals) {
  fixtureMode = true;
  current = { candles: fixture[kind].candles, signals };
  await page.evaluate(() => {
    const raw = JSON.parse(
      localStorage.getItem("wesetrade.charts") ?? '{"state":{},"version":1}',
    );
    raw.state.charts = {
      primary: { symbol: "ETHUSDT", timeframe: "15m" },
      secondary: { symbol: "BTCUSDT", timeframe: "1h" },
    };
    localStorage.setItem("wesetrade.charts", JSON.stringify(raw));
  });
  await page.reload({ waitUntil: "networkidle" });
  await waitReady("primary");
  await waitReady("secondary");
  await page.waitForTimeout(1500);
}

async function insideViewport(locator) {
  const box = await locator.boundingBox();
  const vp = page.viewportSize();
  return (
    box !== null &&
    box.x >= 0 &&
    box.y >= 0 &&
    box.x + box.width <= vp.width + 1 &&
    box.y + box.height <= vp.height + 1
  );
}

async function legendVisibleIn(id) {
  const strip = page.locator(
    `section[data-chart="${id}"] [data-testid="chart-signal-status"]`,
  );
  const button = strip.getByRole("button", { name: "شرح الشارت" });
  const s = await strip.boundingBox();
  const b = await button.boundingBox();
  return s && b && b.x >= s.x - 1 && b.x + b.width <= s.x + s.width + 1;
}

async function hoverMarker(expectSide) {
  const box = await page
    .locator('section[data-chart="primary"] canvas')
    .first()
    .boundingBox();
  for (let x = box.x + box.width - 80; x > box.x + 10; x -= 3) {
    await page.mouse.move(x, box.y + box.height / 2);
    const card = page.getByTestId("signal-marker-card");
    if (
      (await card.count()) > 0 &&
      (await card.innerText()).includes(expectSide)
    )
      return card;
  }
  return null;
}

const BUY = fixture.buy.signal_at_confirmation;
await showFixture("buy", fixture.buy.signals);
const buyStatus = page.locator(
  'section[data-chart="primary"] [data-testid="chart-signal-status"]',
);
check(
  "BUY fixture: status «شراء — اختبار مباشر»",
  (await buyStatus.getAttribute("data-state")) === "buy",
);
const buyText = await buyStatus.innerText();
check(
  "BUY fixture: Entry/SL/TP1-3 + strength shown",
  ["2,485.14", "2,467.73", "2,508.38", "2,518.31", "2,558.56", "81/100"].every(
    (v) => buyText.includes(v),
  ),
);
check(
  "BUY fixture: persisted markers (1 closed + 1 active) on the chart",
  (await (await chartPanel("primary")).getAttribute("data-markers")) === "2",
);
const secondary = page.locator(
  'section[data-chart="secondary"] [data-testid="chart-signal-status"]',
);
check(
  "two charts independent (secondary BTCUSDT 1h: own state, no leaked markers)",
  (await (await chartPanel("secondary")).getAttribute("data-symbol")) ===
    "BTCUSDT" &&
    (await (await chartPanel("secondary")).getAttribute("data-markers")) ===
      "0" &&
    (await secondary.getAttribute("data-state")) !== "buy",
);
await page.screenshot({ path: path.join(OUT, "03-buy-fixture.png") });
const buyCard = await hoverMarker("شراء BUY");
check("BUY marker tooltip on hover", buyCard !== null);
check(
  "BUY status: legend button stays visible",
  await legendVisibleIn("primary"),
);
if (buyCard)
  check(
    "BUY tooltip fully visible (not clipped)",
    await insideViewport(buyCard),
  );
if (buyCard) {
  const t = await buyCard.innerText();
  check(
    "BUY tooltip: fingerprint + not a probability",
    t.includes("4.2-a03e20f") && t.includes("غير معايرة"),
  );
  await page.screenshot({ path: path.join(OUT, "04-buy-tooltip.png") });
}
check(
  "BUY id matches engine fixture",
  BUY.trigger_time === Date.parse("2026-09-18T05:00:00Z") / 1000,
);

// --- fixture mode: the engine's real SELL (at confirmation, then after it was stopped) --------
await page.mouse.move(5, 5);
await showFixture("sell", [fixture.sell.signal_at_confirmation]);
const sellStatus = page.locator(
  'section[data-chart="primary"] [data-testid="chart-signal-status"]',
);
check(
  "SELL fixture: status «بيع — اختبار مباشر»",
  (await sellStatus.getAttribute("data-state")) === "sell",
);
const sellText = await sellStatus.innerText();
check(
  "SELL fixture: plan values",
  ["1,876.00", "1,889.13", "1,857.96", "1,848.16", "1,835.03", "79/100"].every(
    (v) => sellText.includes(v),
  ),
);
await page.screenshot({ path: path.join(OUT, "05-sell-fixture.png") });
const sellCard = await hoverMarker("بيع SELL");
check("SELL marker tooltip on hover", sellCard !== null);
if (sellCard)
  check(
    "SELL tooltip fully visible (not clipped)",
    await insideViewport(sellCard),
  );
if (sellCard)
  await page.screenshot({ path: path.join(OUT, "06-sell-tooltip.png") });

await page.mouse.move(5, 5);
await showFixture("sell", fixture.sell.signals);
check(
  "closed SELL: marker kept, status back to neutral (no plan lines)",
  (await sellStatus.getAttribute("data-state")) === "neutral" &&
    (await (await chartPanel("primary")).getAttribute("data-markers")) === "1",
);
await page.screenshot({ path: path.join(OUT, "07-sell-closed.png") });

// --- desktop resolution 1920x1080 --------------------------------------------------------------
await page.setViewportSize({ width: 1920, height: 1080 });
await page.waitForTimeout(800);
await noOverflow("1920x1080");
await page.screenshot({ path: path.join(OUT, "08-1920.png") });

current = null;
fixtureMode = false;
const relevant = consoleErrors.filter((e) => !/favicon/i.test(e));
check(
  "no console errors",
  relevant.length === 0,
  relevant.slice(0, 3).join(" | "),
);

await browser.close();
const failed = results.filter(([, ok]) => !ok);
console.log(
  `== chart signal E2E: ${results.length - failed.length}/${results.length} checks passed`,
);
process.exit(failed.length ? 1 : 0);
